## m2 stage
FROM zelejs/allin-web:alpine-m2 AS m2

## src stage
FROM zelejs/allin-web:git AS git
# WORKDIR /root/m2
# COPY --from=m2 /root/.m2/settings.xml /root/m2
# RUN echo 'github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl' > /root/.ssh/known_hosts
# RUN echo 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==' >> /root/.ssh/known_hosts
# RUN echo 'github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=' >> /root/.ssh/known_hosts
RUN ssh-keyscan -p 7207 git.f.smallsaas.cn >> ~/.ssh/known_hosts
####################################
WORKDIR /usr/src
#RUN ssh-keyscan github.com > ~/.ssh/known_hosts
#RUN echo "140.82.113.4 github.com" > /etc/hosts
# RUN git clone --depth=1 git@github.com:smallsaas/nft.git --single-branch -b nft-artifact-auth src
RUN git clone ssh://pi@git.f.smallsaas.cn:7207/repo/git/gmic/gmic-cad-users.git --single-branch -b master users \
&& git clone ssh://pi@git.f.smallsaas.cn:7207/repo/git/gmic/gmic-cad-vendor.git --single-branch -b master vendor \
&& git clone ssh://pi@git.f.smallsaas.cn:7207/repo/git/gmic/gmic-cad-report.git --single-branch -b master report \
&& git clone ssh://pi@git.f.smallsaas.cn:7207/repo/git/gmic/gmic-cad-oms.git --single-branch -b master oms \
&& git clone ssh://pi@git.f.smallsaas.cn:7207/repo/git/gmic/gmic-cad-artifact.git --single-branch -b master artifact

######################################


#cache-stage
FROM allin-web:cache-artifact-1 as cache

#builk-stage
FROM maven:3.6-openjdk-11-slim AS build

WORKDIR /root/.m2
COPY --from=cache /root/.m2 /root/.m2

RUN rm -rf /root/.m2/repository/com/jfeat/
## mvn package
WORKDIR /usr/src/users

COPY --from=git /usr/src/users/pom.xml  ./pom.xml
COPY --from=git /usr/src/users/src  ./src
RUN mvn -DskipStandalone=false install -Dmaven.test.skip=true

WORKDIR /usr/src/oms
COPY --from=git /usr/src/oms/pom.xml  ./pom.xml
COPY --from=git /usr/src/oms/src  ./src
RUN mvn -DskipStandalone=false install -Dmaven.test.skip=true
WORKDIR /usr/src/vendor
COPY --from=git /usr/src/vendor/pom.xml  ./pom.xml
COPY --from=git /usr/src/vendor/src  ./src
RUN mvn -DskipStandalone=false install -Dmaven.test.skip=true
WORKDIR /usr/src/report
COPY --from=git /usr/src/report/pom.xml  ./pom.xml
COPY --from=git /usr/src/report/src  ./src
RUN mvn -DskipStandalone=false install -Dmaven.test.skip=true
WORKDIR /usr/src/artifact
COPY --from=git /usr/src/artifact/pom.xml ./pom.xml
COPY --from=git /usr/src/artifact/src ./src
RUN mvn -DskipStandalone=false package -Dmaven.test.skip=true

#final-stage
CMD ["sh", "-c", "/bin/cp /usr/src/artifact/target/*-standalone.jar /var/webapps"]
